/**
 * Kiswahili. The key is the English sentence exactly as the screens write it.
 *
 * NOT REVIEWED: these were not written by a native speaker and must be read by one before a member
 * sees them. The loan words follow the Wakandi Member App concept (unadaiwa, rudisha, lipa sasa).
 */
export const sw: Record<string, string> = {
  // ── shell, navigation ──
  'Home': 'Mwanzo',
  'Language': 'Lugha',
  'Choose one.': 'Chagua moja.',
  'The app changes to the language you choose.': 'Programu hubadilika kwenda lugha unayochagua.',
  'Loans': 'Mikopo',
  'My loans': 'Mikopo yangu',
  'Pay': 'Lipa',
  'Profile': 'Wasifu',
  'Main': 'Menyu kuu',
  'Member': 'Mwanachama',
  'Sign out': 'Toka',
  'Back': 'Rudi',
  'Close': 'Funga',
  'Cancel': 'Ghairi',
  'Change': 'Badilisha',
  'Continue': 'Endelea',
  'Try again': 'Jaribu tena',
  'Refresh': 'Onyesha upya',
  'Loading': 'Inapakia',
  'Something went wrong': 'Hitilafu imetokea',
  'Showing the last saved details.': 'Tunaonyesha taarifa zilizohifadhiwa mwisho.',
  'You are offline. Check your data or Wi-Fi.': 'Huna mtandao. Angalia data yako au Wi-Fi.',
  'See all': 'Ona yote',
  'View': 'Ona',
  'Track': 'Fuatilia',
  'Back to home': 'Rudi mwanzo',
  'Thank you.': 'Asante.',

  // ── time ──
  'Today': 'Leo',
  'Earlier': 'Awali',
  'today': 'leo',
  'just now': 'sasa hivi',
  '{a} min ago': 'dakika {a} zilizopita',
  '{a} h ago': 'saa {a} zilizopita',
  '{a} d ago': 'siku {a} zilizopita',
  '{a} ago': '{a} zilizopita',
  'in {a}': 'baada ya {a}',
  '{a} left': 'Zimebaki {a}',

  // ── home ──
  'Hello': 'Habari',
  'Hello, {a}': 'Habari, {a}',
  'Application in progress': 'Ombi linashughulikiwa',
  'View application status': 'Ona hali ya ombi',
  'You can borrow up to': 'Unaweza kukopa hadi',
  'You have no loan now': 'Huna mkopo sasa',
  'You have no loan now.': 'Huna mkopo sasa.',
  'Pay back within {a}': 'Rudisha ndani ya {a}',
  'Apply for loan': 'Omba mkopo',
  'No loan available right now': 'Hakuna mkopo kwa sasa',
  'Your lender decides who can borrow using its own rules and your repayment history.': 'Mkopeshaji wako huamua nani anaweza kukopa kwa kutumia kanuni zake na historia yako ya kulipa.',
  'You can apply again after you pay back this loan.': 'Unaweza kuomba tena baada ya kulipa mkopo huu.',
  'You already have an application in progress.': 'Tayari una ombi linaloshughulikiwa.',
  'Loans you can get after you pay back': 'Mikopo unayoweza kupata baada ya kulipa',
  '{a} · borrow {b}, pay back {c}': '{a} · kopa {b}, rudisha {c}',
  'Your loan offers': 'Ofa zako za mkopo',
  'Special offer': 'Ofa maalum',
  'Up to {a}': 'Hadi {a}',
  'Up to': 'Hadi',
  'Recent activity': 'Yaliyotokea karibuni',
  'Nothing yet': 'Bado hakuna',
  'Updates about your loans will appear here.': 'Taarifa kuhusu mikopo yako zitaonekana hapa.',
  'Loan behaviour: {a} / 100': 'Tabia ya mkopo: {a} / 100',
  '{a}% paid back on time': '{a}% imelipwa kwa wakati',
  '{a} in a row': '{a} mfululizo',

  // ── the loan, and being late ──
  'Your loan': 'Mkopo wako',
  'Your loan · more time given {a}×': 'Mkopo wako · umepewa muda zaidi mara {a}',
  'Your payment is late': 'Malipo yako yamechelewa',
  'Pay today': 'Lipa leo',
  'You owe': 'Unadaiwa',
  'It was due on {a}.': 'Ilitakiwa kulipwa {a}.',
  'That was {a} ago.': 'Ni {a} zilizopita.',
  'Pay today to stay on time': 'Lipa leo ili usichelewe',
  'Pay it back before <b>{a}</b> · {b} left': 'Rudisha kabla ya <b>{a}</b> · zimebaki {b}',
  '{a}% paid back': '{a}% imelipwa',
  'Paying late has added {a}. Pay as soon as you can so it does not cost more.': 'Kuchelewa kulipa kumeongeza {a}. Lipa haraka uwezavyo ili isigharimu zaidi.',
  'Paying late has added {a}.': 'Kuchelewa kulipa kumeongeza {a}.',
  'Pay now': 'Lipa sasa',
  'View loan': 'Ona mkopo',
  'View my loan': 'Ona mkopo wangu',
  'Late': 'Imechelewa',
  'late': 'imechelewa',
  'Late · {a} ago': 'Imechelewa · {a} zilizopita',
  'Late by': 'Umechelewa kwa',
  'On time': 'Kwa wakati',

  // ── applying ──
  'Apply for a loan': 'Omba mkopo',
  'Confirm your loan': 'Thibitisha mkopo wako',
  'Step {a} of 2': 'Hatua {a} kati ya 2',
  'There is no loan offer for you at the moment.': 'Hakuna ofa ya mkopo kwako kwa sasa.',
  'Which loan?': 'Mkopo gani?',
  'How much do you need?': 'Unahitaji kiasi gani?',
  'Loan amount': 'Kiasi cha mkopo',
  'Max': 'Juu',
  'Borrow only what you need.': 'Kopa kile unachohitaji tu.',
  'The smallest amount is {a}.': 'Kiasi cha chini ni {a}.',
  'You can borrow up to {a}.': 'Unaweza kukopa hadi {a}.',
  'You get now': 'Unapata sasa',
  'Pay it back before': 'Rudisha kabla ya',
  'You pay back': 'Utarudisha',
  'It costs <b>{a}</b> to borrow {b} for {c}.': 'Inagharimu <b>{a}</b> kukopa {b} kwa {c}.',
  'It costs nothing to borrow {b} for {c}.': 'Haigharimu chochote kukopa {b} kwa {c}.',
  '{a} from {b}': '{a} kutoka {b}',
  'Interest ({a}% a month)': 'Riba ({a}% kwa mwezi)',
  'Interest': 'Riba',
  'Fee': 'Ada',
  'Fees': 'Ada',
  'Cost of the loan': 'Gharama ya mkopo',
  'Money sent to': 'Pesa itatumwa kwa',
  'If you pay late': 'Ukichelewa kulipa',
  'Paying late costs more: <b>{a}</b>.': 'Kuchelewa kulipa kunagharimu zaidi: <b>{a}</b>.',
  'Paying late does not cost more, but it is written on your record.': 'Kuchelewa kulipa hakugharimu zaidi, lakini huandikwa kwenye rekodi yako.',
  'If you do not pay, you are given more time automatically. Each time costs a {a}% fee. This can happen up to {b} times.': 'Usipolipa, unapewa muda zaidi moja kwa moja. Kila mara inagharimu ada ya {a}%. Hii inaweza kutokea hadi mara {b}.',
  'You can pay a {a}% fee to get {c} more days, up to {b} times.': 'Unaweza kulipa ada ya {a}% ili kupata siku {c} zaidi, hadi mara {b}.',
  'You cannot get more time on this loan.': 'Huwezi kupata muda zaidi kwa mkopo huu.',
  'Paying late lowers your loan behaviour score and may be reported to credit reference bureaus (CRB).': 'Kuchelewa kulipa hupunguza alama yako ya tabia ya mkopo na kunaweza kuripotiwa kwa ofisi za taarifa za mikopo (CRB).',
  'You can pay in parts at any time.': 'Unaweza kulipa kidogo kidogo wakati wowote.',
  'Pay back early and it costs less: you save {a}% of the interest for the days you did not use.': 'Ukilipa mapema inagharimu kidogo: unaokoa {a}% ya riba ya siku ambazo hukutumia.',
  'I understand how much I pay back, by when, and what happens if I pay late. I accept these terms.': 'Ninaelewa kiasi nitakachorudisha, lini, na kinachotokea nikichelewa kulipa. Ninakubali masharti haya.',
  'Your consent for credit bureau checks is on file.': 'Ruhusa yako ya ukaguzi wa CRB imehifadhiwa.',
  'I allow {a} to check my credit bureau (CRB) record for this application.': 'Ninaruhusu {a} kukagua rekodi yangu ya CRB kwa ombi hili.',
  'Yes, apply for {a}': 'Ndiyo, omba {a}',
  'Change amount': 'Badilisha kiasi',
  'We couldn’t submit your application. Please try again.': 'Hatukuweza kutuma ombi lako. Tafadhali jaribu tena.',

  // ── application status ──
  'Application status': 'Hali ya ombi',
  'Application sent': 'Ombi limetumwa',
  'Application not approved': 'Ombi halijakubaliwa',
  'Not approved': 'Halijakubaliwa',
  'Waiting for your lender': 'Tunasubiri mkopeshaji wako',
  'Money sent': 'Pesa imetumwa',
  'Money delayed': 'Pesa imechelewa',
  'Sent to your lender': 'Limetumwa kwa mkopeshaji wako',
  'Being checked': 'Linakaguliwa',
  'Approved': 'Limekubaliwa',
  'Sending to M-PESA': 'Inatumwa kwa M-PESA',
  'Your lender checks this loan before saying yes. You will get an SMS as soon as there is a decision. You can close this screen.': 'Mkopeshaji wako hukagua mkopo huu kabla ya kukubali. Utapata SMS mara uamuzi utakapofanyika. Unaweza kufunga skrini hii.',
  'Your lender was unable to approve this application.': 'Mkopeshaji wako hakuweza kukubali ombi hili.',
  'We could not send the money to M-PESA yet. Your lender has been told and will retry.': 'Bado hatujaweza kutuma pesa kwa M-PESA. Mkopeshaji wako amejulishwa na atajaribu tena.',
  'You borrow': 'Unakopa',
  'Time to pay back': 'Muda wa kulipa',
  'Sent. Waiting for an answer.': 'Limetumwa. Linasubiri jibu.',
  'Your lender is checking this application.': 'Mkopeshaji wako anakagua ombi hili.',
  'Approved. The money is being sent.': 'Limekubaliwa. Pesa inatumwa.',
  'The money is on its way to your M-PESA.': 'Pesa iko njiani kwenda M-PESA yako.',
  'Approved, but the money is delayed. Your lender will try again.': 'Limekubaliwa, lakini pesa imechelewa. Mkopeshaji wako atajaribu tena.',

  // ── my loans ──
  'Now': 'Sasa',
  'Waiting': 'Inasubiri',
  'Paid back': 'Imelipwa',
  'When you take a loan it will appear here.': 'Ukichukua mkopo utaonekana hapa.',
  'No applications in progress': 'Hakuna ombi linaloshughulikiwa',
  'Loan applications waiting for a decision appear here.': 'Maombi ya mkopo yanayosubiri uamuzi huonekana hapa.',
  'No finished loans yet': 'Bado hakuna mkopo uliomalizika',
  'Loans you have paid back appear here.': 'Mikopo uliyomaliza kulipa huonekana hapa.',
  'Nothing is late': 'Hakuna kilichochelewa',
  'You have no late payments.': 'Huna malipo yaliyochelewa.',
  'What I have paid': 'Nilicholipa',
  'Past payments and statements': 'Malipo ya nyuma na taarifa',
  'Was due': 'Ilitakiwa',
  'Was due on': 'Ilitakiwa kulipwa',
  'Pay back by': 'Rudisha kabla ya',
  'Borrowed': 'Ulikopa',
  'early': 'mapema',
  'on time': 'kwa wakati',
  'after the due date': 'baada ya tarehe ya kulipa',
  '{a} paid of {b}': 'Umelipa {a} kati ya {b}',
  'Taken {a}': 'Ulichukua {a}',
  'Amount': 'Kiasi',
  'Applied': 'Uliomba',
  'No loans yet': 'Bado hakuna mikopo',

  // ── one loan ──
  'Loan details': 'Maelezo ya mkopo',
  'All paid back': 'Umelipa yote',
  'Paid back early.': 'Umelipa mapema.',
  'Paid back on time.': 'Umelipa kwa wakati.',
  'Paid back late.': 'Umelipa kwa kuchelewa.',
  'About this loan': 'Kuhusu mkopo huu',
  'You borrowed': 'Ulikopa',
  'Fees for more time': 'Ada za muda zaidi',
  'Added for paying late': 'Imeongezwa kwa kuchelewa',
  'Saved by paying early': 'Umeokoa kwa kulipa mapema',
  'You have paid': 'Umelipa',
  'You still owe': 'Bado unadaiwa',
  'Days left': 'Siku zilizobaki',
  'What you owe now': 'Unachodaiwa sasa',
  'Money you borrowed': 'Pesa uliyokopa',
  'Fees, and extra for paying late': 'Ada, na nyongeza ya kuchelewa',
  'All together': 'Jumla',
  'If you pay late: {a}.': 'Ukichelewa kulipa: {a}.',
  'Paying late does not cost more on this loan.': 'Kuchelewa kulipa hakugharimu zaidi kwa mkopo huu.',
  'More time used: {a} of {b} times.': 'Muda zaidi umetumika: mara {a} kati ya {b}.',
  'When to pay': 'Wakati wa kulipa',
  'One payment · before {a}': 'Malipo moja · kabla ya {a}',
  '{a} of {b} paid': 'Umelipa {a} kati ya {b}',
  'Payments': 'Malipo',
  'No payments yet.': 'Bado hakuna malipo.',
  'No payments yet': 'Bado hakuna malipo',
  'Payments you make will appear here.': 'Malipo utakayofanya yataonekana hapa.',
  '{a}: payment of {b} did not go through. What you owe did not change.': '{a}: malipo ya {b} hayakupita. Unachodaiwa hakijabadilika.',
  'Download statement (PDF)': 'Pakua taarifa (PDF)',
  'Download my loan statement (PDF)': 'Pakua taarifa ya mkopo wangu (PDF)',
  'Saved {a} to your downloads.': '{a} imehifadhiwa kwenye vipakuliwa vyako.',
  'View terms': 'Ona masharti',
  'Loan terms': 'Masharti ya mkopo',
  'You borrowed <b>{a}</b> under <b>{b}</b> for {c} and agreed to pay back <b>{d}</b> by {e}.': 'Ulikopa <b>{a}</b> chini ya <b>{b}</b> kwa {c} na ulikubali kurudisha <b>{d}</b> kabla ya {e}.',
  '{a}% per month': '{a}% kwa mwezi',
  'None': 'Hakuna',
  'Paying in parts': 'Kulipa kidogo kidogo',
  'Allowed': 'Inaruhusiwa',
  'Not allowed': 'Hairuhusiwi',
  'Saving if you pay early': 'Unachookoa ukilipa mapema',
  '{a}% of the interest for unused days': '{a}% ya riba ya siku ambazo hukutumia',
  'No extra cost': 'Hakuna gharama ya ziada',
  'More time to pay': 'Muda zaidi wa kulipa',
  'Up to {a} times, {b} days each, {c}% fee each time': 'Hadi mara {a}, siku {b} kila mara, ada ya {c}% kila mara',
  'Up to {a} times': 'Hadi mara {a}',
  '(automatic)': '(moja kwa moja)',

  // ── more time to pay ──
  'Can’t pay it all? You can get more time: pay <b>{a}</b> now and you have until <b>{b}</b> to pay the rest. Times you can do this: {c}.': 'Huwezi kulipa yote? Unaweza kupata muda zaidi: lipa <b>{a}</b> sasa na utakuwa na hadi <b>{b}</b> kulipa kilichobaki. Unaweza kufanya hivi mara: {c}.',
  'Get more time to pay': 'Pata muda zaidi wa kulipa',
  'You now have more time to pay.': 'Sasa una muda zaidi wa kulipa.',
  'This gives you more days to pay. It costs money, so only use it if you cannot pay everything on time.': 'Hii inakupa siku zaidi za kulipa. Inagharimu pesa, kwa hivyo itumie tu ikiwa huwezi kulipa yote kwa wakati.',
  'You pay now': 'Unalipa sasa',
  'Of that, the fee for more time': 'Kati ya hizo, ada ya muda zaidi',
  'Then pay it back before': 'Kisha rudisha kabla ya',
  'You will still owe': 'Bado utadaiwa',
  'Times you can do this again': 'Mara unazoweza kufanya hivi tena',

  // ── paying ──
  'Pay back': 'Lipa mkopo',
  'Nothing to pay': 'Hakuna cha kulipa',
  'Time': 'Muda',
  'Part paid · {a} left': 'Umelipa sehemu · zimebaki {a}',
  'Recent payments': 'Malipo ya karibuni',
  'Make a payment': 'Fanya malipo',
  'This loan is all paid back': 'Mkopo huu umelipwa wote',
  'There is nothing more to pay.': 'Hakuna cha kulipa tena.',
  'Pay it all today': 'Lipa yote leo',
  '{a} (you save {b})': '{a} (unaokoa {b})',
  'What is in this amount': 'Kilichomo kwenye kiasi hiki',
  'How much will you pay?': 'Utalipa kiasi gani?',
  'Enter an amount.': 'Weka kiasi.',
  'The most you can pay is {a}.': 'Kiasi cha juu unachoweza kulipa ni {a}.',
  'This loan is paid back in one payment ({a}).': 'Mkopo huu hulipwa kwa malipo moja ({a}).',
  'This loan is paid back in one payment of {a}.': 'Mkopo huu hulipwa kwa malipo moja ya {a}.',
  'Any amount, up to {a}': 'Kiasi chochote, hadi {a}',
  'Pay everything · {a}': 'Lipa yote · {a}',
  'Pay part of the amount': 'Lipa sehemu ya kiasi',
  'Pay {a}': 'Lipa {a}',
  'You will check the amount and number before anything is sent.': 'Utakagua kiasi na namba kabla ya chochote kutumwa.',
  'Pay from': 'Lipa kutoka',
  'My M-PESA number': 'Namba yangu ya M-PESA',
  'Another M-PESA number': 'Namba nyingine ya M-PESA',
  'The payment request goes to that phone, and its owner confirms with their M-PESA PIN.': 'Ombi la malipo huenda kwenye simu hiyo, na mwenye simu huthibitisha kwa PIN yake ya M-PESA.',
  'M-PESA number to pay from': 'Namba ya M-PESA ya kulipia',
  'Enter a valid M-PESA number, e.g. 0712 345 678.': 'Weka namba sahihi ya M-PESA, mfano 0712 345 678.',
  'your M-PESA number': 'namba yako ya M-PESA',
  'your phone': 'simu yako',
  'Check this': 'Angalia hii',
  'You are paying': 'Unalipa',
  'M-PESA number': 'Namba ya M-PESA',
  'After this payment': 'Baada ya malipo haya',
  'This pays it all': 'Hii inalipa yote',
  'Yes, pay {a}': 'Ndiyo, lipa {a}',
  'You will receive an M-PESA prompt on <b>{a}</b>. Enter your M-PESA PIN to complete the payment.': 'Utapata ombi la M-PESA kwenye <b>{a}</b>. Weka PIN yako ya M-PESA ili kukamilisha malipo.',
  'An M-PESA prompt will be sent to <b>{a}</b>. The owner of that phone enters their M-PESA PIN to complete the payment.': 'Ombi la M-PESA litatumwa kwa <b>{a}</b>. Mwenye simu hiyo huweka PIN yake ya M-PESA ili kukamilisha malipo.',
  'Nothing is taken until the M-PESA PIN is entered.': 'Hakuna pesa inayochukuliwa hadi PIN ya M-PESA iwekwe.',
  'Demo: an amount of exactly KES 999 simulates a failed payment.': 'Onyesho: kiasi cha KES 999 kamili huiga malipo yaliyoshindikana.',

  // ── waiting for M-PESA, and the result ──
  'Confirm on your phone': 'Thibitisha kwenye simu yako',
  'Check your phone': 'Angalia simu yako',
  'We sent an M-PESA request for <b>{a}</b> to <b>{b}</b>.': 'Tumetuma ombi la M-PESA la <b>{a}</b> kwa <b>{b}</b>.',
  'Enter your M-PESA PIN to confirm.': 'Weka PIN yako ya M-PESA ili kuthibitisha.',
  'The owner of that phone enters their M-PESA PIN to confirm.': 'Mwenye simu hiyo huweka PIN yake ya M-PESA ili kuthibitisha.',
  'Waiting for M-PESA…': 'Tunasubiri M-PESA…',
  'Waiting for M-PESA': 'Tunasubiri M-PESA',
  'Please keep this screen open. Do not pay twice.': 'Tafadhali acha skrini hii wazi. Usilipe mara mbili.',
  'M-PESA has not told us about your <b>{a}</b> yet. This can take a few minutes on a slow network.': 'M-PESA bado haijatujulisha kuhusu <b>{a}</b> yako. Hii inaweza kuchukua dakika chache mtandao ukiwa wa polepole.',
  'Please do not pay again yet': 'Tafadhali usilipe tena kwa sasa',
  'If you entered your M-PESA PIN, what you owe will go down as soon as M-PESA confirms, and you will get an SMS. If you did not get a prompt, wait a moment and check again.': 'Ikiwa uliweka PIN yako ya M-PESA, unachodaiwa kitapungua mara M-PESA itakapothibitisha, na utapata SMS. Ikiwa hukupata ombi kwenye simu, subiri kidogo kisha angalia tena.',
  'Check again': 'Angalia tena',
  'Did not get the request on your phone?': 'Hukupata ombi kwenye simu yako?',
  'Send it again': 'Tuma tena',
  'Send it again in {a} seconds': 'Tuma tena baada ya sekunde {a}',
  'We sent the request again. Check your phone.': 'Tumetuma ombi tena. Angalia simu yako.',
  'If two requests reach the phone, approve only one.': 'Maombi mawili yakifika kwenye simu, thibitisha moja tu.',
  'We have not received a confirmation from M-PESA yet. If you approved the payment, your loan will update shortly. Please do not pay again.': 'Bado hatujapata uthibitisho kutoka M-PESA. Ikiwa ulithibitisha malipo, mkopo wako utasasishwa hivi karibuni. Tafadhali usilipe tena.',
  'Payment received': 'Malipo yamepokelewa',
  'Payment did not go through': 'Malipo hayakupita',
  'We received {a}. Thank you.': 'Tumepokea {a}. Asante.',
  'The payment did not go through. What you owe has not changed.': 'Malipo hayakupita. Unachodaiwa hakijabadilika.',
  'The payment did not go through. Your loan has not changed.': 'Malipo hayakupita. Mkopo wako haujabadilika.',
  'You paid': 'Umelipa',
  'M-PESA receipt': 'Risiti ya M-PESA',
  'Paid from': 'Imelipwa kutoka',
  'Loan all paid back': 'Mkopo umelipwa wote',
  'Well done. Your loan behaviour has been updated.': 'Hongera. Tabia yako ya mkopo imesasishwa.',
  'See my loan behaviour': 'Ona tabia yangu ya mkopo',
  'Pay the rest': 'Lipa kilichobaki',
  'Successful': 'Imefanikiwa',
  'Still owed': 'Bado unadaiwa',
  'saved {a}': 'umeokoa {a}',
  'paid from {a}': 'imelipwa kutoka {a}',
  'Paid in full': 'Umelipa yote',
  'Part payment': 'Malipo ya sehemu',
  'Paid for more time': 'Malipo ya muda zaidi',
  'Cash': 'Pesa taslimu',
  'Bank': 'Benki',
  'Cheque': 'Hundi',

  // ── notifications ──
  'Notifications': 'Arifa',
  'Notifications, {a} unread': 'Arifa, {a} hazijasomwa',
  'No notifications yet': 'Bado hakuna arifa',
  'Updates about your applications, loans and payments will appear here.': 'Taarifa kuhusu maombi, mikopo na malipo yako zitaonekana hapa.',
  '{a} unread': '{a} hazijasomwa',
  'All caught up': 'Umesoma zote',
  'Mark all as read': 'Weka zote kuwa zimesomwa',
  'Important notifications are also sent to your phone by SMS.': 'Arifa muhimu pia hutumwa kwenye simu yako kwa SMS.',
  'New': 'Mpya',
  'Application': 'Ombi',
  'Delayed': 'Imechelewa',
  'Payment': 'Malipo',
  'Payment failed': 'Malipo hayakufanikiwa',
  'Loan paid back': 'Mkopo umelipwa',
  'More time': 'Muda zaidi',
  'Late cost': 'Gharama ya kuchelewa',
  'Reminder': 'Kikumbusho',
  'Loan offer': 'Ofa ya mkopo',
  'CRB status': 'Hali ya CRB',
  'Update': 'Taarifa',
  'Pay soon': 'Lipa karibuni',

  // ── profile ──
  'My loan behaviour': 'Tabia yangu ya mkopo',
  'My CRB status': 'Hali yangu ya CRB',
  'Phone number': 'Namba ya simu',
  'ID number': 'Namba ya kitambulisho',
  'SACCO / lender': 'SACCO / mkopeshaji',
  'M-PESA number for loans': 'Namba ya M-PESA ya mikopo',
  'These details come from your SACCO and cannot be changed here. To correct anything, including your phone number, contact your SACCO.': 'Taarifa hizi zinatoka kwa SACCO yako na haziwezi kubadilishwa hapa. Ili kurekebisha chochote, ikiwemo namba yako ya simu, wasiliana na SACCO yako.',
  'Change PIN': 'Badilisha PIN',
  'Current PIN': 'PIN ya sasa',
  'New PIN (4 digits)': 'PIN mpya (tarakimu 4)',
  'Save PIN': 'Hifadhi PIN',
  'Your PIN has been changed.': 'PIN yako imebadilishwa.',

  // ── an offer from an SMS link ──
  'offer for you': 'ofa kwa ajili yako',
  'Valid until {a}': 'Inatumika hadi {a}',
  'You have already applied using this offer.': 'Tayari umeomba kwa kutumia ofa hii.',
  'This offer has expired.': 'Ofa hii imeisha muda.',
  'Apply for this loan': 'Omba mkopo huu',
  'Example': 'Mfano',
  'Borrow {a}, pay back {b}': 'Kopa {a}, rudisha {b}',
  'An offer shows the most you may borrow. Borrow only what you need. You will see what it costs and when to pay it back before you apply.': 'Ofa inaonyesha kiasi cha juu unachoweza kukopa. Kopa kile unachohitaji tu. Utaona gharama yake na lini kurudisha kabla ya kuomba.',

  // ── status badges ──
  'Sent': 'Limetumwa',
  'Rejected': 'Limekataliwa',
  'Sending money': 'Pesa inatumwa',
  'Defaulted': 'Haujalipwa',
  'More time given': 'Umepewa muda zaidi',
  'Expired': 'Imeisha muda',
  'Completed': 'Imekamilika',
  'Failed': 'Imeshindikana',
  'Pending': 'Inasubiri',
  'Partly paid': 'Imelipwa sehemu',
  'Paid': 'Imelipwa',
  'Submitted': 'Imewasilishwa',
  'One-time offer': 'Ofa ya mara moja',
  'Ongoing': 'Inaendelea',
};
